import "../styles/globals.scss";
import { Providers } from "./providers";
import type { Metadata } from "next";
import ContentLayout from "@components/layouts/ContentLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="light">
      <body>
        <Providers>
          <ContentLayout>{children}</ContentLayout>
        </Providers>
      </body>
    </html>
  );
}
